<?php


namespace backend\models;

use yii\db\ActiveRecord;

/**
 * @property int $id [int(11)]
 * @property string $title [varchar(255)]
 */

class Categories extends ActiveRecord
{
    public static function tableName()
    {
        return '{{%categories}}'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['title'], 'string'],
            [['title'], 'required']
        ];
    }
}