<?php


namespace backend\models;

use yii\db\ActiveRecord;

/**
 * @property int $id [int(11)]
 * @property int $type_id [int(11)]
 * @property string $title [varchar(255)]
 * @property TransportTypes $transportType
 */

class Transports extends ActiveRecord
{
    public static function tableName()
    {
        return '{{%transports}}'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [['title', 'type_id'], 'required'],
            [['title'], 'string'],
            [['type_id'], 'integer']
        ];
    }

    public function getTransportType() {
        return $this->hasOne(TransportTypes::class, ['id' => 'type_id']);
    }
}