<?php


namespace frontend\models;


use yii\db\ActiveRecord;

/**
 * Class Advertisement
 * @package frontend\models
 * @property int $id [int(11)]
 * @property string $name [varchar(255)]
 * @property string $address [varchar(255)]
 * @property string $area [varchar(255)]
 * @property string $region [varchar(255)]
 * @property string $city [varchar(255)]
 * @property string $year [varchar(255)]
 * @property string $price [varchar(255)]
 * @property string $description
 */
class Advertisement extends ActiveRecord
{
    public static function tableName()
    {
        return 'advertisements'; // TODO: Change the autogenerated stub
    }

    public function rules()
    {
        return [
            [
                ['name', 'id', 'address', 'area', 'region', 'city', 'year', 'price', 'description'], 'safe'
            ]
        ]; // TODO: Change the autogenerated stub
    }
}